name: Delete old releases
on:
  workflow_dispatch:
    inputs:
      startDate:
        type: text
        required: true
        description: enter the date in YYYY-mm-dd format
        default: "2024-01-01"
        
jobs:
  delete-releases:
    runs-on: ubuntu-latest
    steps:
    - run: |
        # for i in $(gh release list --repo https://github.com/github/safe-settings --json createdAt,tagName --limit 1000 --jq '.[] | select(.createdAt < ${{ inputs.startDate }} ) | .tagName'); do gh release delete --repo https://github.com/github/safe-settings $i --cleanup-tag  -y; done
        gh release list --repo https://github.com/github/safe-settings --json createdAt,tagName --limit 1000 --jq '.[] | select(.createdAt < ${{ inputs.startDate }} ) | .tagName'
    
